# Use root/example as user/password credentials
version: '3.1'

services:
  #   app:
  #     image: node-app
  #     ports:
  #       - 3000:3000
  #
  #     depends_on:
  #       mongo:
  #         condition: service_healthy

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}

    volumes:
      - mongodbdata:/data/db

    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081

    depends_on:
      mongo:
        condition: service_healthy

    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGODB_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGODB_PASSWORD}

      # ME_CONFIG_MONGODB_ENABLE_ADMIN: true
      # ME_CONFIG_BASICAUTH_USERNAME: ${MONGODB_USERNAME}
      # ME_CONFIG_BASICAUTH_PASSWORD: ${MONGODB_PASSWORD}

      ME_CONFIG_MONGODB_URL: mongodb://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@mongo:27017/

volumes:
  mongodbdata:

